spring.application.name=api-autores-obras
spring.datasource.url=jdbc:postgresql://localhost:5432/db_autores_obras
spring.datasource.username=postgres
spring.datasource.password=2010
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true